name: First Workflow
on: workflow_dispatch
on:
  push:
    branches:
      - auto-build
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Done - bye"
        
